import type { Category, CategoryId } from './types'

export const BUILTIN_CATEGORIES: Category[] = [
  {
    id: 'housing',
    label: 'Wohnen & Miete',
    bucket: 'fixed',
    builtin: true,
    keywords: [
      'miete',
      'mietzins',
      'nebenkosten',
      'hausverwaltung',
      'wohnung',
      'immobilien',
      'wohnbau',
      'vermiet',
      'kaution',
      'hausgeld',
      'wohngeld',
      'grundsteuer',
    ],
  },
  {
    id: 'loans',
    label: 'Kredite & Darlehen',
    bucket: 'fixed',
    builtin: true,
    keywords: [
      'darlehen',
      'kredit',
      'tilgung',
      'annuitaet',
      'annuität',
      'ratenzahlung',
      'finanzierung',
      'baufinanzierung',
      'leasing',
      'santander',
      'targobank',
      'easycredit',
      'consors finanz',
      'bnp paribas',
      'creditplus',
      'younited',
      'auxmoney',
      'kfw',
      'ratenkredit',
      'zinsen',
    ],
  },
  {
    id: 'insurance',
    label: 'Versicherungen',
    bucket: 'fixed',
    builtin: true,
    keywords: [
      'versicherung',
      'assekuranz',
      'allianz',
      'axa',
      'huk',
      'ergo',
      'debeka',
      'signal iduna',
      'gothaer',
      'zurich',
      'generali',
      'wuerttembergische',
      'württembergische',
      'provinzial',
      'lvm',
      'devk',
      'barmenia',
      'continentale',
      'hansemerkur',
      'dev k',
      'r+v',
      'r + v',
      'vhv',
      'adac',
      'haftpflicht',
      'hausrat',
      'rechtsschutz',
      'lebensvers',
      'rentenvers',
      'berufsunfaehigkeit',
      'unfallvers',
      'kfz-vers',
      'krankenvers',
      'zusatzvers',
      'pflegevers',
      'sterbegeld',
      'riester',
      'ruerup',
      'rürup',
    ],
  },
  {
    id: 'health',
    label: 'Krankenkasse & Gesundheit',
    bucket: 'fixed',
    builtin: true,
    keywords: [
      'krankenkasse',
      'aok',
      'barmer',
      'tk techniker',
      'techniker krankenkasse',
      'dak',
      'ikk',
      'bkk',
      'kkh',
      'hkk',
      'knappschaft',
      'siemens-betriebskrankenkasse',
      'pronova',
      'mhplus',
      'audi bkk',
      'securvita',
      'beitrag kv',
      'kassenbeitrag',
    ],
  },
  {
    id: 'utilities',
    label: 'Strom, Gas & Wasser',
    bucket: 'fixed',
    builtin: true,
    keywords: [
      'stadtwerke',
      'energie',
      'strom',
      'gasversorgung',
      'erdgas',
      'eon',
      'e.on',
      'e wie einfach',
      'vattenfall',
      'rwe',
      'enbw',
      'yello',
      'lichtblick',
      'naturstrom',
      'octopus energy',
      'tibber',
      'wasserwerk',
      'wasserversorgung',
      'abwasser',
      'entsorgung',
      'abfall',
      'muellabfuhr',
      'müllabfuhr',
      'fernwaerme',
      'fernwärme',
      'heizung',
      'heizoel',
      'heizöl',
      'netze bw',
      'versorgungsbetriebe',
    ],
  },
  {
    id: 'telecom',
    label: 'Telefon & Internet',
    bucket: 'fixed',
    builtin: true,
    keywords: [
      'telekom',
      'vodafone',
      'o2',
      'telefonica',
      'telefónica',
      '1&1',
      '1und1',
      'congstar',
      'aldi talk',
      'blau.de',
      'klarmobil',
      'winsim',
      'simquadrat',
      'pyur',
      'unitymedia',
      'kabel deutschland',
      'netcologne',
      'm-net',
      'ewe tel',
      'htp',
      'mobilfunk',
      'internet',
      'dsl',
      'festnetz',
      'glasfaser',
      'lycamobile',
      'fraenk',
      'freenet',
    ],
  },
  {
    id: 'subscriptions',
    label: 'Abos & Streaming',
    bucket: 'fixed',
    builtin: true,
    keywords: [
      'netflix',
      'spotify',
      'amazon prime',
      'prime video',
      'disney',
      'dazn',
      'sky deutschland',
      'wow tv',
      'apple.com/bill',
      'apple services',
      'itunes',
      'google play',
      'youtube',
      'paramount',
      'wondery',
      'audible',
      'deezer',
      'tidal',
      'mubi',
      'crunchyroll',
      'adobe',
      'microsoft 365',
      'office 365',
      'dropbox',
      'icloud',
      'openai',
      'chatgpt',
      'notion',
      'canva',
      'linkedin premium',
      'xing',
      'fitnessstudio',
      'mcfit',
      'fitx',
      'clever fit',
      'urban sports',
      'gym',
      'zeitung',
      'abonnement',
      'abo ',
      'mitgliedsbeitrag',
      'verein',
      'gewerkschaft',
      'nachhilfe',
    ],
  },
  {
    id: 'fees',
    label: 'Gebühren & Abgaben',
    bucket: 'fixed',
    builtin: true,
    keywords: [
      'kontofuehrung',
      'kontoführung',
      'kontogebuehr',
      'kontogebühr',
      'entgeltabschluss',
      'rechnungsabschluss',
      'gebuehren',
      'gebühren',
      'kartenpreis',
      'jahrespreis',
      'depotgebuehr',
      'depotpreis',
      'rundfunk',
      'rundfunkbeitrag',
      'ard zdf',
      'beitragsservice',
      'gez',
      'kammerbeitrag',
      'ihk',
      'hwk',
      'kfz-steuer',
      'kraftfahrzeugsteuer',
      'hauptzollamt',
      'bundeskasse',
      'stadtkasse',
      'gemeindekasse',
      'finanzamt',
      'steuer',
      'kirchensteuer',
      'mahngebuehr',
      'saeumniszuschlag',
      'säumniszuschlag',
    ],
  },
  {
    id: 'savings',
    label: 'Sparen & Vorsorge',
    bucket: 'fixed',
    builtin: true,
    keywords: [
      'sparplan',
      'sparvertrag',
      'vermoegensbildung',
      'vermögensbildung',
      'bausparen',
      'bausparkasse',
      'schwaebisch hall',
      'schwäbisch hall',
      'wuestenrot',
      'wüstenrot',
      'ltbs',
      'depot',
      'trade republic',
      'scalable capital',
      'comdirect',
      'flatex',
      'union invest',
      'dws',
      'deka',
      'fondssparplan',
      'etf',
      'ruecklage',
      'rücklage',
      'vwl',
      'riesterrente',
    ],
  },
  {
    id: 'transport_fixed',
    label: 'Mobilität (fix)',
    bucket: 'fixed',
    builtin: true,
    keywords: [
      'deutschlandticket',
      'jobticket',
      'monatskarte',
      'abo-ticket',
      'bahncard',
      'db vertrieb',
      'verkehrsverbund',
      'vrr',
      'vvs',
      'mvg',
      'rmv',
      'hvv',
      'bvg',
      'kvb',
      'stadtverkehr',
      'parkplatz',
      'stellplatz',
      'garage',
      'tiefgarage',
      'carsharing',
    ],
  },
  {
    id: 'childcare',
    label: 'Kinder & Bildung',
    bucket: 'fixed',
    builtin: true,
    keywords: [
      'kita',
      'kindergarten',
      'kinderbetreuung',
      'krippe',
      'hort',
      'schulgeld',
      'elternbeitrag',
      'jugendamt',
      'musikschule',
      'studiengebuehr',
      'studiengebühr',
      'semesterbeitrag',
      'unterhalt',
      'kindesunterhalt',
    ],
  },
  {
    id: 'groceries',
    label: 'Lebensmittel & Einkauf',
    bucket: 'variable',
    builtin: true,
    keywords: [
      'rewe',
      'edeka',
      'aldi',
      'lidl',
      'kaufland',
      'penny',
      'netto',
      'norma',
      'real ',
      'globus',
      'famila',
      'combi',
      'tegut',
      'denns',
      'alnatura',
      'bio company',
      'dm-drogerie',
      'dm filiale',
      'rossmann',
      'mueller ',
      'müller ',
      'baecker',
      'bäcker',
      'baeckerei',
      'bäckerei',
      'metzger',
      'fleischerei',
      'getraenke',
      'getränke',
      'supermarkt',
      'wochenmarkt',
      'hofladen',
      'action',
      'tedi',
      'woolworth',
      'kodi',
    ],
  },
  {
    id: 'fuel',
    label: 'Tanken & Auto',
    bucket: 'variable',
    builtin: true,
    keywords: [
      'tankstelle',
      'aral',
      'shell',
      'esso',
      'jet ',
      'total',
      'agip',
      'avia',
      'star tankstelle',
      'hem ',
      'raiffeisen tank',
      'oil!',
      'sprint tank',
      'clean car',
      'waschanlage',
      'autohaus',
      'kfz-werkstatt',
      'werkstatt',
      'atu',
      'pitstop',
      'vergoelst',
      'reifen',
      'tuev',
      'tüv',
      'dekra',
      'ladestrom',
      'ionity',
      'ewe go',
      'ladesaeule',
      'ladesäule',
      'maut',
    ],
  },
  {
    id: 'dining',
    label: 'Restaurant & Freizeit',
    bucket: 'variable',
    builtin: true,
    keywords: [
      'restaurant',
      'gaststaette',
      'gaststätte',
      'pizzeria',
      'imbiss',
      'cafe',
      'café',
      'bistro',
      'baeckerei cafe',
      'mcdonald',
      'burger king',
      'kfc',
      'subway',
      'nordsee',
      'starbucks',
      'lieferando',
      'wolt',
      'uber eats',
      'too good to go',
      'kino',
      'cinemaxx',
      'cineplex',
      'schwimmbad',
      'therme',
      'zoo',
      'freizeitpark',
      'eventim',
      'ticketmaster',
      'hotel',
      'booking.com',
      'airbnb',
      'apotheke',
    ],
  },
  {
    id: 'shopping',
    label: 'Shopping & Sonstiges',
    bucket: 'variable',
    builtin: true,
    keywords: [
      'amazon.de',
      'amzn',
      'otto',
      'zalando',
      'about you',
      'h&m',
      'c&a',
      'zara',
      'peek cloppenburg',
      'deichmann',
      'saturn',
      'mediamarkt',
      'media markt',
      'notebooksbilliger',
      'cyberport',
      'ikea',
      'obi',
      'bauhaus',
      'hornbach',
      'toom',
      'hagebau',
      'thalia',
      'hugendubel',
      'douglas',
      'paypal',
      'klarna',
      'ebay',
      'etsy',
      'temu',
      'shein',
      'decathlon',
      'intersport',
    ],
  },
  {
    id: 'cash',
    label: 'Bargeld',
    bucket: 'variable',
    builtin: true,
    keywords: [
      'bargeldauszahlung',
      'barauszahlung',
      'geldautomat',
      'auszahlung',
      'gaa ',
      'atm ',
      'cash group',
      'bargeld',
    ],
  },
  {
    id: 'income',
    label: 'Einnahmen',
    bucket: 'income',
    builtin: true,
    keywords: [
      'lohn',
      'gehalt',
      'bezuege',
      'bezüge',
      'entgelt',
      'honorar',
      'rente',
      'pension',
      'kindergeld',
      'familienkasse',
      'elterngeld',
      'arbeitslosengeld',
      'bundesagentur',
      'jobcenter',
      'erstattung',
      'gutschrift',
      'steuererstattung',
      'dividende',
      'zinsertrag',
    ],
  },
  {
    id: 'transfer',
    label: 'Umbuchung & Eigenkonto',
    bucket: 'ignored',
    builtin: true,
    keywords: [
      'umbuchung',
      'uebertrag',
      'übertrag',
      'eigenuebertrag',
      'kreditkartenabrechnung',
      'kreditkartenausgleich',
      'visa abrechnung',
      'mastercard abrechnung',
      'ausgleich kreditkarte',
      'tagesgeld',
      'girocard aufladung',
      'auf eigenes konto',
      'zwischen eigenen konten',
    ],
  },
  {
    id: 'other_fixed',
    label: 'Sonstige Fixkosten',
    bucket: 'fixed',
    builtin: true,
    keywords: [],
  },
  {
    id: 'uncategorized',
    label: 'Nicht zugeordnet',
    bucket: 'variable',
    builtin: true,
    keywords: [],
  },
]

export const CATEGORY_MAP = new Map<CategoryId, Category>(
  BUILTIN_CATEGORIES.map((c) => [c.id, c]),
)

/** Buchungstexte, die stark auf eine wiederkehrende Belastung hindeuten. */
const RECURRING_BOOKING_TEXTS = [
  'dauerauftrag',
  'folgelastschrift',
  'basislastschrift',
  'erstlastschrift',
  'lastschrift',
  'einzugsermaechtigung',
  'einzugsermächtigung',
  'abschlag',
  'sepa-dauerauftrag',
  'miete',
  'darlehen',
]

export function looksRecurringByBookingText(bookingText: string): boolean {
  const lower = bookingText.toLowerCase()
  return RECURRING_BOOKING_TEXTS.some((t) => lower.includes(t))
}

/**
 * Ordnet einer Buchung anhand von Empfänger, Verwendungszweck und Buchungstext
 * eine Kategorie zu. Gibt die Kategorie mit dem längsten Keyword-Treffer zurück,
 * damit spezifische Begriffe ("kfz-versicherung") allgemeine ("steuer") schlagen.
 */
export function categorize(
  counterparty: string,
  purpose: string,
  bookingText: string,
  amount: number,
  categories: Category[],
): CategoryId {
  // Drei Informationsquellen mit unterschiedlicher Aussagekraft:
  // 1. Verwendungszweck – benennt das konkrete Produkt/den Vertrag
  // 2. Empfängername – benennt nur das Unternehmen
  // 3. Buchungstext – bankinterner Buchungstyp, am unspezifischsten
  //    (die Sparkasse bucht Darlehensraten als "ENTGELTABSCHLUSS")
  const what = purpose.toLowerCase()
  const who = counterparty.toLowerCase()
  const how = bookingText.toLowerCase()

  // Interne Umbuchungen niemals als Ausgaben behandeln – auch dann nicht,
  // wenn der Empfängername zufällig wie ein Händlername wirkt.
  const transferMarkers = [
    'umbuchung',
    'uebertrag',
    'übertrag',
    'eigenübertrag',
    'eigenuebertrag',
    'auf eigenes konto',
    'zwischen eigenen konten',
    'kreditkartenabrechnung',
    'kreditkartenausgleich',
  ]
  if (amount < 0 && transferMarkers.some((marker) => `${what} ${who} ${how}`.includes(marker))) {
    return categories.some((category) => category.id === 'transfer') ? 'transfer' : 'uncategorized'
  }

  // Supermarktzahlungen sind variable Einzelkosten. Sie dürfen deshalb nicht
  // von der Serien-/Fixkostenlogik abhängen.
  const groceryMerchants = [
    'aldi',
    'edeka',
    'kaufland',
    'lidl',
    'netto',
    'norma',
    'penny',
    'rewe',
    'globus',
    'famila',
    'combi',
    'tegut',
    'denns',
    'alnatura',
  ]
  if (
    amount < 0 &&
    groceryMerchants.some((merchant) => `${what} ${who}`.includes(merchant)) &&
    categories.some((category) => category.id === 'groceries')
  ) {
    return 'groceries'
  }

  let bestCategory: CategoryId | null = null
  let bestScore = 0

  for (const category of categories) {
    if (category.keywords.length === 0) continue
    // Bei Ausgaben keine Einnahmen-Kategorie zuordnen ...
    if (category.bucket === 'income' && amount < 0) continue
    // ... und bei Eingängen keine Kostenkategorie. Sonst landet z. B. das
    // Kindergeld der "Familienkasse" über ein Keyword in den Fixkosten.
    if (category.bucket !== 'income' && amount > 0) continue

    for (const keyword of category.keywords) {
      if (!keyword) continue

      // Gewichtung nach Aussagekraft der Quelle
      const weight = what.includes(keyword)
        ? 1.6
        : who.includes(keyword)
          ? 1
          : how.includes(keyword)
            ? 0.7
            : 0
      if (weight === 0) continue

      let score = keyword.length * weight
      // Nutzerdefinierte Kategorien haben Vorrang
      if (category.custom) score += 100

      if (score > bestScore) {
        bestScore = score
        bestCategory = category.id
      }
    }
  }

  if (bestCategory) return bestCategory

  if (amount > 0) return 'income'
  return 'uncategorized'
}

export function getCategory(id: CategoryId, categories: Category[]): Category {
  return (
    categories.find((c) => c.id === id) ??
    CATEGORY_MAP.get('uncategorized') ?? {
      id: 'uncategorized',
      label: 'Nicht zugeordnet',
      bucket: 'variable',
      keywords: [],
    }
  )
}
